name: Style checking

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  style:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: "2.10.1"

      - name: Fetch submodule
        run: git submodule update --init --recursive

      - name: Checkout main in submodule
        run: git submodule foreach git checkout main

      - name: Install dependencies
        run: flutter pub get

      - name: Formatting
        run: flutter format --output=none --set-exit-if-changed .

      - name: Analyze
        run: flutter analyze
